version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - bdd-ynov-immo-5:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    stdin_open: true
    tty: true

volumes: 
  bdd-ynov-immo-5:
    external: true
    name: bdd-ynov-immo-5
